In [1]:
# data = [line.strip().split(';') for line in open('18-k2.csv')]
# print(*data, sep='\n')

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2, 1],
              [0,-1, 1],
              [1, 0, 2]])
A

array([[ 1,  2,  1],
       [ 0, -1,  1],
       [ 1,  0,  2]])

In [4]:
X = np.array([1, -1, 2])

In [5]:
B = A @ X
B

array([1, 3, 5])

In [6]:
np.linalg.det(A)

1.0

In [7]:
np.linalg.solve(A, B)

array([ 1., -1.,  2.])

In [28]:
A = np.eye(28, dtype=int)*6
A[0, [1,7]] = -1
A[1, [0,2,7,8]] = -1
A[2, [1,3,8,9]] = -1
A[3, [2,4,9,10]] = -1
A[4, [3,5,10,11]] = -1
A[5, [4,6,11,12]] = -1
A[6, [5,12]] = -1
A[7, [0,1,8,13]] = -1
A[8, [1,2,7,9,13,14]] = -1
A[9, [2,3,8,10,14,15]] = -1
A[10, [3,4,9,11,15,16]] = -1
A[11, [4,5,10,12,16,17]] = -1
A[12, [5,6,11,17]] = -1
A[13, [7,8,14,18]] = -1
A[14, [8,9,13,15,18,19]] = -1
A[15, [9,10,14,16,19,20]] = -1
A[16, [10,11,15,17,20,21]] = -1
A[17, [11,12,16,21]] = -1
A[18, [13,14,19,22]] = -1
A[19, [14,15,18,20,22,23]] = -1
A[20, [15,16,19,21,23,24]] = -1
A[21, [16,17,20,24]] = -1
A[22, [18,19,23,25]] = -1
A[23, [19,20,22,24,25,26]] = -1
A[24, [20,21,23,26]] = -1
A[25, [21,22,26,27]] = -1
A[26, [22,23,25,27]] = -1
A[27, [25,26]] = -1

B = np.array([ 3, 5, 7, 9,11,13,15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int)
A, B

(array([[ 6, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [-1,  6, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, -1,  6, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0, -1,  6, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, -1,  6, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  6, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, -1,  6,  0,  0,  0,  0,  0, -1,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [-1, -1,  0,  0,  0,  0,  0,  6, -1,  0,  0,  0,  0, -1,  0,  0,
          

In [29]:
np.linalg.det(A)

4.0038966848710476e+20

In [30]:
X = np.linalg.solve(A, B)
X

array([0.9438215 , 1.8288578 , 2.64412593, 3.36122223, 3.91321448,
       4.13070481, 3.50011499, 0.83407123, 1.55112816, 2.1235474 ,
       2.48644555, 2.50091429, 1.86998513, 0.68061989, 1.19554669,
       1.50281583, 1.51695909, 1.08817667, 0.50297328, 0.81219559,
       0.88220068, 0.6412015 , 0.32947754, 0.46015949, 0.35987256,
       0.20153686, 0.17567372, 0.06286843])

In [32]:
np.round(A @ X, 10)

array([ 3.,  5.,  7.,  9., 11., 13., 15.,  0.,  0., -0., -0.,  0.,  0.,
        0., -0., -0., -0., -0.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0.,
        0.,  0.])

In [25]:
round(6*X[8] - np.sum(X[[1,2,7,9,13,14]]), 10)

0.0

In [26]:
X[15]

1.5028158314075952